// VUE/futbolvue/src/components/Menu.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Tenth navbar example">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample08"
            aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <router-link class="nav-link active" to="/new">Apuestas</router-link>
                </li>
                <li class="nav-item dropdown">
                    <span class="nav-link dropdown-toggle" id="desplegable" data-bs-toggle="dropdown"
                        aria-expanded="false">Equipos</span>
                    <ul class="dropdown-menu" aria-labelledby="desplegable">
                        <li v-for="(equipo, index) in equipos" :key="index">
                            <router-link :to="'/equipos/'+equipo.idEquipo" class="dropdown-item">{{equipo.nombre}}</router-link></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
</template>

<script>
import Equipos from '../services/equipos'

const service = new Equipos()
export default {
    name: "Menu",
    data(){
        return{
            equipos: []
        }
    },
    mounted(){
        this.cargarEquipos()
    },
    methods:{
        cargarEquipos(){
            service.getEquipos().then(res=>{
                this.equipos = res
            })
        }
    }
}
</script>

// ANGULAR/championangular/src/app/Components/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { ChampiosService } from 'src/app/Services/champions.service';
import { Equipo } from 'src/app/Models/Equipo';
@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  public equipos!:Array<Equipo>

  constructor(
    private _service:ChampiosService
  ) { }

  ngOnInit(): void {
    this.cargarEquipos();
  }

  cargarEquipos(){
    this._service.getEquipos().subscribe(res=>{
      this.equipos = res
    })
  }

}

<nav
  class="navbar navbar-expand-lg navbar-dark bg-dark"
  aria-label="Tenth navbar example"
>
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarsExample08"
      aria-controls="navbarsExample08"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div
      class="collapse navbar-collapse justify-content-md-center"
      id="navbarsExample08"
    >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a [routerLink]="['/apuestas']" class="nav-link active">Apuestas</a>
        </li>
        <li class="nav-item dropdown">
          <span
            class="nav-link dropdown-toggle"
            id="desplegable"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            >Equipos</span
          >
          <ul class="dropdown-menu" aria-labelledby="desplegable">
            <li *ngFor="let equipo of equipos">
              <a
                [routerLink]="['/equipo', equipo.idEquipo]"
                class="dropdown-item"
                >{{ equipo.nombre }}</a
              >
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
