// EXAMEN/Examen - 19 de noviembre/examenangularbolq/src/app/Components/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Genero } from 'src/app/Models/Genero';
import { Nacionalidad } from 'src/app/Models/Nacionalidad';
import { PeliculaService } from 'src/app/Services/pelicula.service';
import { Router } from '@angular/router';


@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  public generos!: Array<Genero>
  public nacionalidades!: Array<Nacionalidad>
  public buscar!:string

  constructor(private _service: PeliculaService, private _router:Router) { }

  ngOnInit(): void {
    this.cargarPeliculasGenero()
    this.cargarPeliculasNacionalidad()
  }

  cargarPeliculasGenero(){
    this._service.getGeneros().subscribe(res=>{
      this.generos = res;
    })
  }

  cargarPeliculasNacionalidad(){
    this._service.getNacionalidad().subscribe(res=>{
      this.nacionalidades = res
    })
  }

  buscarPeliculas(){
    this._router.navigate(['/buscador',this.buscar])
  }

}

<nav
  class="navbar navbar-expand-lg navbar-light bg-light"
  aria-label="Tenth navbar example"
>
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarsExample08"
      aria-controls="navbarsExample08"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div
      class="collapse navbar-collapse justify-content-md-start"
      id="navbarsExample08"
    >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a [routerLink]="['/']" class="nav-link active">HOME</a>
        </li>
        <li class="nav-item dropdown">
          <span
            class="nav-link dropdown-toggle"
            id="desplegable"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            >Generos</span
          >
          <ul class="dropdown-menu" aria-labelledby="desplegable">
            <li *ngFor="let genero of generos">
              <a
                [routerLink]="['/peliculasGenero', genero.idGenero]"
                class="dropdown-item"
                >{{ genero.nombre }}</a
              >
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <span
            class="nav-link dropdown-toggle"
            id="desplegable"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            >Nacionalidades</span
          >
          <ul class="dropdown-menu" aria-labelledby="desplegable">
            <li *ngFor="let nacionalidad of nacionalidades">
              <a
                [routerLink]="[
                  '/peliculasNacionalidad',
                  nacionalidad.idNacionalidad
                ]"
                class="dropdown-item"
                >{{ nacionalidad.nombre
                }}<img src="{{ nacionalidad.bandera }}" style="width: 50px"
              /></a>
            </li>
          </ul>
        </li>
      </ul>
      <form #formBuscar class="d-flex">
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
          name="buscar"
          #buscarCaja
          [(ngModel)]="buscar"
        />
        <a
          (click)="buscarPeliculas()"
          class="btn btn-outline-success"
          type="button"
          >Search</a
        >
      </form>
    </div>
  </div>
</nav>

// VUE/proyectoapivue/src/components/Menu.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Tenth navbar example">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample08"
            aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample08">
            <img src="./../assets/img/LOGO_PERSONAL.png" class="rounded-circle border border-2 border-white" width="75px"/>
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                <li class="nav-item">
                    <router-link to="/" class="nav-link active">Home</router-link>
                </li>
                <li class="nav-item">
                    <router-link to="/coches" class="nav-link active">Coches</router-link>
                </li>
                <li class="nav-item">
                    <router-link to="/empleado" class="nav-link active">Detalles empleado</router-link>
                </li>
                <li class="nav-item">
                    <router-link to="/oficios" class="nav-link active">Detalles oficios</router-link>
                </li>
                <li class="nav-item">
                    <router-link to="/servicios" class="nav-link active">Servicios</router-link>
                </li>
                <li class="nav-item dropdown">
                    <span class="nav-link dropdown-toggle" id="desplegable" data-bs-toggle="dropdown"
                        aria-expanded="false">Empleados</span>
                    <ul class="dropdown-menu" aria-labelledby="desplegable">
                        <li><router-link to="/empleado" class="dropdown-item">Detalles empleado</router-link></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="text" placeholder="Buscar" aria-label="Search">
                <button class="btn btn-outline-success">Buscar</button>
            </form>
        </div>
    </div>
</nav>
</template>

<script>
export default {
    name: "Menu",

}
</script>
