// VUE/multiplicarvue/src/components/navegacion/Numeros.vue
<template>
    <div>
        <h1>Numeros Padre</h1>
        <button @click="insertarHijo()">Crear hijo</button>
        <h2 v-if="numeroRes">Resultado de los hijos: {{numeroRes}}</h2>
        <div v-for="(num,index) in arrayNumeros" :key="index">
            <Numero style="color:purple" :alea="num" v-on:metodoPadre="sumarHijos"/>
        </div>
    </div>
</template>

<script>
import Numero from './Numero.vue'

export default {
    name: "Numeros",
    data(){
        return{
            numeroRes: 0,
            arrayNumeros: []
        }
    },methods: {
        sumarHijos(num){
            this.numeroRes += parseInt(num)
        },
        aleatorio(){
            let dado = parseInt((Math.random()*50)+1);
            return dado;
        },crearHijos(){
            this.numeroRes = 0;
            this.arrayNumeros =[];
            for (let i = 0; i < 3; i++) {
                this.arrayNumeros.push(this.aleatorio())
            }
        },insertarHijo(){
            var aleatorio = this.aleatorio();
            this.arrayNumeros.push(aleatorio)
        }
    },components:{
        Numero
    },created(){
        this.crearHijos();
    }
}
</script>

// REACT/reactclases/src/Components/Numeros/Numeros.js
import { Component } from "react";
import Numero from "../Numero/Numero";
class Numeros extends Component {
  state = {
    numerosHijo: [1, 2, 3, 4],
    resultado: 0,
  };

  sumar = (num) => {
    var res = parseInt(num) + parseInt(this.state.resultado);
    this.setState({
      resultado: res,
    });
  };

  generarAleatorio = () => {
    let aleatorio = parseInt(Math.random() * 10) + 1;
    this.state.numerosHijo.push(aleatorio);
    this.setState({
      numerosHijo: this.state.numerosHijo,
    });
  };
  render() {
    return (
      <div>
        <div>
          <h1>Resultado: {this.state.resultado}</h1>
          <button onClick={() => this.generarAleatorio()}>
            generar numero
          </button>
        </div>
        <hr />
        <table>
          {this.state.numerosHijo.map((objNum, index) => {
            return <Numero Num={objNum} key={index} MetodoSumar={this.sumar} />;
          })}
        </table>
      </div>
    );
  }
}

export default Numeros;
