// VUE/proyectoapivue/src/components/EmpleadosOficio.vue
<template>
    <div>
        <h1>Oficios</h1>
        <div class="row justify-content-center">
            <div class="col-6 text-center">
                <form method="post">
                    <label class="form-label fw-bold">Seleccione un oficio</label>
                    <select v-on:change.prevent="mostrarOficio" v-model="idOficio" class="form-control">
                        <option v-for="(oficio, index) in oficios" :key="index" :value="oficio">{{oficio}}</option>
                    </select>
                </form>
            </div>
        </div>
        <div v-if="empleados.length != 0" class="row justify-content-center mt-5">
            <div class="col-8 text-center">
                <table class="table table-striped table-hover table-responsive table-bordered border-dark">
                    <thead class="fw-bold" style="background-color: midnightblue; color: white;">
                        <tr>
                            <td>Apellido</td>
                            <td>Departamento</td>
                            <td>Oficio</td>
                            <td>Salario</td>
                        </tr>
                    </thead>
                    <tbody class="table-info table-bordered border-dark">
                        <tr v-for="(empleado,index) in empleados" :key="index">
                            <td>{{empleado.apellido}}</td>
                            <td>{{empleado.departamento}}</td>
                            <td>{{empleado.oficio}}</td>
                            <td>{{empleado.salario}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios';
import Global from './Global'
export default {
    name: "EmpleadosOficio",
    data(){
        return{
            oficios: [],
            idOficio: 0,
            empleados: [],
        }
    },methods:{
        cargarOficios(){
            var request = "/api/Empleados/oficios";
            var url = Global.urlEmpleados + request;
            axios.get(url).then(res=>{
                this.oficios = res.data;
                console.log(res.data)

            })
        },mostrarOficio(){
            var request = "/api/Empleados/EmpleadosOficio/"+this.idOficio;
            var url = Global.urlEmpleados + request;
            axios.get(url).then(res=>{
                this.empleados = res.data
                console.log(res.data)
            })
        }
    },mounted(){
        this.cargarOficios();
    }
}
</script>

// ANGULAR/serviciosangular/src/app/Components/empleados-oficio/empleados-oficio.component.ts
import { Component, OnInit } from '@angular/core';
import { EmpleadoOficioService } from 'src/app/Services/empleadoOficio.service';
import { EmpleadoOficio } from 'src/app/Models/EmpleadoOficio';

@Component({
  selector: 'app-empleados-oficio',
  templateUrl: './empleados-oficio.component.html',
  styleUrls: ['./empleados-oficio.component.css']
})
export class EmpleadosOficioComponent implements OnInit {

  constructor(private _service: EmpleadoOficioService) { }

  public empleadosOficios!: Array<EmpleadoOficio>;
  public oficios!: Array<string>;
  public oficio!: string;

  ngOnInit(): void {
    this._service.getOficio().subscribe(res=>{
      this.oficios = res
    })
  }

  getEmpleados(){
    this._service.getEmpleadosOficio(this.oficio).subscribe(res=>{
      this.empleadosOficios = res
    })
  }

}

<h1 class="text-center">Empleados mediante el oficio</h1>

<div class="row justify-content-center mt-5">
  <div
    class="col-4 rounded-3"
    style="
      background-color: lightgreen;
      border: solid 3px darkgreen;
      color: darkgreen;
    "
  >
    <form #formOficios="ngForm" class="text-center p-4 fw-bold">
      <div class="mb-3">
        <h3>Buscar Empleado con el Oficio</h3>
      </div>
      <div class="mb-3">
        <label class="form-label">Oficio:</label>
        <select
          (change)="getEmpleados()"
          class="form-control"
          name="oficio"
          #oficioSelect
          [(ngModel)]="oficio"
        >
          <option *ngFor="let oficio of oficios">{{ oficio }}</option>
        </select>
      </div>
    </form>
  </div>
</div>

<div class="row justify-content-center mt-5">
  <div class="col-8 text-center">
    <table
      class="
        table table-striped table-hover table-responsive table-bordered
        border-dark
      "
    >
      <thead
        class="fw-bold"
        style="background-color: midnightblue; color: white"
      >
        <tr>
          <td>Id</td>
          <td>Apellido</td>
          <td>Oficio</td>
          <td>Salario</td>
          <td>Departamento</td>
        </tr>
      </thead>
      <tbody class="table-info table-bordered border-dark">
        <tr *ngFor="let empleado of empleadosOficios">
          <td>{{ empleado.idEmpleado }}</td>
          <td>{{ empleado.apellido }}</td>
          <td>{{ empleado.oficio }}</td>
          <td>{{ empleado.salario }}</td>
          <td>{{ empleado.departamento }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
