// VUE/futbolvue/src/components/Apuestas.vue
<template>

    <div>
         <div class="row justify-content-center mt-5">
            <div class="col-6 text-center">
              <router-link to="/newApuesta" class="btn btn-danger">
                Realizar Apuesta
              </router-link>
            </div>
          </div>
          <div class="row text-danger text-center mt-3">
            <h1>Local: Real Madrid, Visitante: Atlético de Madrid</h1>
          </div>
        <div class="row justify-content-center mt-5">
            <div class="col-8 text-center">
                <table class="table table-striped table-hover table-responsive table-bordered border-dark">
                    <thead class="fw-bold" style="background-color: midnightblue; color: white;">
                        <tr>
                            <td>USUARIO</td>
                            <td>RESULTADO</td>
                            <td>FECHA</td>
                        </tr>
                    </thead>
                    <tbody class="table-info table-bordered border-dark">
                        <tr v-for="(apuesta,index) in apuestas" :key="index">
                            <td>{{apuesta.usuario}}</td>
                            <td>{{apuesta.resultado}}</td>
                            <td>{{apuesta.fecha}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</template>

<script>
import Equipos from '../services/equipos'

const service = new Equipos();
export default {
    name: "Apuestas",
    data(){
        return{
            apuestas: [],

        }
    },mounted(){
        this.cargarApuestas()
    },methods:{
        cargarApuestas(){
            service.getApuestas().then(res=>{
                this.apuestas = res
            })
        }
    }
}
</script>

// ANGULAR/championangular/src/app/Components/apuestas/apuestas.component.ts
import { Component, OnInit } from '@angular/core';
import { ChampiosService } from 'src/app/Services/champions.service';
import { Apuesta } from 'src/app/Models/Apuesta';


@Component({
  selector: 'app-apuestas',
  templateUrl: './apuestas.component.html',
  styleUrls: ['./apuestas.component.css']
})
export class ApuestasComponent implements OnInit {

  public apuestas!: Array<Apuesta>
  public idApuesta!: number;

  constructor(
    private _service: ChampiosService
  ) { }

  ngOnInit(): void {
    this.cargarApuestas();
  }

  cargarApuestas(){
    this._service.getApuestas().subscribe(res=>{
      this.apuestas = res;
    })
  }

  cargarIdApuesta(id: number){
    this.idApuesta = id;
  }

  eliminarApuesta(){
    this._service.deleteApuesta(this.idApuesta.toString()).subscribe(res=>{
      this.cargarApuestas();
    })
  }

}

<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Confirmación</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <h1>¿Desea eliminar?</h1>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Cancelar
        </button>
        <button
          type="button"
          class="btn btn-danger"
          data-bs-dismiss="modal"
          (click)="eliminarApuesta()"
        >
          Eliminar
        </button>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center my-5">
  <div class="col-6 text-center">
    <a [routerLink]="['/newApuesta']" class="btn btn-outline-danger"
      >Nueva Apuesta</a
    >
  </div>
</div>
<h1 class="text-danger text-center">
  Local: Real Madrid, Visitante: Atletico de Madrid
</h1>

<div *ngIf="!apuestas" class="d-flex justify-content-center">
  <div class="spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

<div *ngIf="apuestas" class="row justify-content-center mt-5">
  <div class="col-8 text-center">
    <table
      class="
        table table-striped table-hover table-responsive table-bordered
        border-dark
      "
    >
      <thead
        class="fw-bold"
        style="background-color: midnightblue; color: white"
      >
        <tr>
          <td>usuario</td>
          <td>resultado</td>
          <td>fecha</td>
          <td>Accion</td>
        </tr>
      </thead>
      <tbody class="table-info table-bordered border-dark">
        <tr *ngFor="let apuesta of apuestas">
          <td>{{ apuesta.usuario }}</td>
          <td>{{ apuesta.resultado }}</td>
          <td>{{ apuesta.fecha }}</td>
          <td>
            <button
              type="button"
              class="btn btn-outline-danger"
              data-bs-toggle="modal"
              data-bs-target="#exampleModal"
              (click)="cargarIdApuesta(apuesta.idApuesta)"
            >
              Eliminar
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
