// ANGULAR/angularcruddepartamentos/src/app/Components/insertar-departamento/insertar-departamento.component.ts
import { Component, OnInit } from '@angular/core';
import { DepartamentoService } from 'src/app/Services/departamentos.service';
import { Departamento } from 'src/app/Models/Departamento';
//para redireccionar
import { Router } from '@angular/router';

@Component({
  selector: 'app-insertar-departamento',
  templateUrl: './insertar-departamento.component.html',
  styleUrls: ['./insertar-departamento.component.css']
})
export class InsertarDepartamentoComponent implements OnInit {

  //debo obtener los datos en string y despues modificarlo
  public numero!: string;
  public nombre!: string;
  public localidad!: string;

  constructor(private _service: DepartamentoService, private _router: Router) {

   }

   insertarDepartamento() : void{
     var departamento = new Departamento(parseInt(this.numero),this.nombre,this.localidad)
      this._service.insertDepartamento(departamento).subscribe(res=>{
        this._router.navigate(["/departamento"]);
      })
   }

  ngOnInit(): void {
  }

}

<div class="row justify-content-center mt-5">
  <div
    class="col-4 rounded-3"
    style="
      background-color: lightgreen;
      border: solid 3px darkgreen;
      color: darkgreen;
    "
  >
    <form #formDepartamento="ngForm" class="text-center p-4 fw-bold">
      <div class="mb-3">
        <h3>INSERTAR DEPARTAMENTO</h3>
      </div>
      <div class="mb-3">
        <label class="form-label">Número:</label>
        <input
          class="form-control"
          type="text"
          placeholder="introduzca el numero"
          name="number"
          #numeroCaja
          [(ngModel)]="numero"
        />
      </div>

      <div class="mb-3">
        <label class="form-label">Nombre:</label>
        <input
          class="form-control"
          type="text"
          placeholder="introduzca el nombre"
          name="name"
          #nombreCaja
          [(ngModel)]="nombre"
        />
      </div>

      <div class="mb-3">
        <label class="form-label">Localidad:</label>
        <input
          class="form-control"
          type="text"
          placeholder="introduzca la localidad"
          name="localidad"
          #localidadCaja
          [(ngModel)]="localidad"
        />
      </div>

      <button
        (click)="insertarDepartamento()"
        class="btn btn-outline-success"
        type="button"
      >
        Insertar
      </button>
    </form>
  </div>
</div>

// VUE/proyectoapivue/src/components/Departamentos/InsertarDepartamento.vue
<template>
    <div>
        <h1>Insertar Departamento</h1>
        <div class="row justify-content-center mt-5">
            <div class="col-4 rounded-3" style="background-color: lightgreen; border: solid 3px darkgreen; color: darkgreen;">
                <form method="post" class="text-center p-4 fw-bold" v-on:submit.prevent="insertarDepartamentos()">
                    <div class="mb-3">
                        <h3>INSERTAR</h3>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Numero:</label>
                        <input class="form-control" type="text" placeholder="introduzca un numero" v-model="departamento.numero" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Nombre:</label>
                        <input class="form-control" type="text" placeholder="introduzca un nombre" v-model="departamento.nombre" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Localidad:</label>
                        <input class="form-control" type="text" placeholder="introduzca la localidad" v-model="departamento.localidad" />
                    </div>

                    <button class="btn btn-outline-success" type="submit">Insertar Departamento</button>

                </form>
            </div>
        </div>
    </div>
</template>

<script>
import ServiceDepartamentos from '../../services/ServiceDepartamentos'

const service = new ServiceDepartamentos;
export default {
    name:"InsertarDepartamentos",
    methods:{
        insertarDepartamentos() {
            //cambiamos el numero en string a int

            this.departamento.numero = parseInt(this.departamento.numero)
            service.insertarDept(this.departamento).then(res=>{
                console.log(res)
                this.mensaje = "Insertado"
                this.$router.push("/serviciosDepartamentos")
            })
        },
    },data(){
        return{
            mensaje:"",
            departamento: {
                numero: 0,
                nombre: "",
                localidad: ""
            },
        }
    }
}
</script>
