// VUE/proyectoapivue/src/components/Departamentos/DetallesDepartamento.vue
<template>
    <div>
        <h1>Detalles Departamento</h1>
        <router-link to="/serviciosDepartamentos" class="btn btn-outline-info">Volver a la lista</router-link>
        <h2 style="color:purple">{{departamento.nombre + " , " +departamento.localidad}}</h2>
    </div>
</template>

<script>
export default {
    name:"DetallesDepartamento",
    mounted(){
        this.departamento.numero = this.$route.params.idDept
        this.departamento.nombre = this.$route.params.nombre
        this.departamento.localidad = this.$route.params.localidad
    },
    data(){
        return {
            departamento: {
                numero: 0,
                nombre: "",
                localidad: ""
            }
        }
    }
}
</script>

// REACT/reactservicios/src/Components/Departamentos/DetallesDepartamento.js
import React, { Component } from "react";
import { NavLink } from "react-router-dom";

export default class DetallesDepartamento extends Component {
  render() {
    return (
      <div>
        <h1>Detalles Departamento</h1>
        <h2>Número: {this.props.idDept}</h2>
        <h2>Nombre: {this.props.nomDept}</h2>
        <h2>Localidad: {this.props.locDept}</h2>
        <NavLink to={"/departamentos"} className="btn btn-outline-secondary">
          Volver al Listado
        </NavLink>

        <NavLink
          to={"/updateDepartamentos/" + this.props.idDept}
          className="btn btn-outline-warning"
        >
          Editar
        </NavLink>
      </div>
    );
  }
}
