// VUE/proyectoapivue/src/components/Departamentos/InsertarDepartamento.vue
<template>
    <div>
        <h1>Insertar Departamento</h1>
        <div class="row justify-content-center mt-5">
            <div class="col-4 rounded-3" style="background-color: lightgreen; border: solid 3px darkgreen; color: darkgreen;">
                <form method="post" class="text-center p-4 fw-bold" v-on:submit.prevent="insertarDepartamentos()">
                    <div class="mb-3">
                        <h3>INSERTAR</h3>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Numero:</label>
                        <input class="form-control" type="text" placeholder="introduzca un numero" v-model="departamento.numero" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Nombre:</label>
                        <input class="form-control" type="text" placeholder="introduzca un nombre" v-model="departamento.nombre" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Localidad:</label>
                        <input class="form-control" type="text" placeholder="introduzca la localidad" v-model="departamento.localidad" />
                    </div>

                    <button class="btn btn-outline-success" type="submit">Insertar Departamento</button>

                </form>
            </div>
        </div>
    </div>
</template>

<script>
import ServiceDepartamentos from '../../services/ServiceDepartamentos'

const service = new ServiceDepartamentos;
export default {
    name:"InsertarDepartamentos",
    methods:{
        insertarDepartamentos() {
            //cambiamos el numero en string a int

            this.departamento.numero = parseInt(this.departamento.numero)
            service.insertarDept(this.departamento).then(res=>{
                console.log(res)
                this.mensaje = "Insertado"
                this.$router.push("/serviciosDepartamentos")
            })
        },
    },data(){
        return{
            mensaje:"",
            departamento: {
                numero: 0,
                nombre: "",
                localidad: ""
            },
        }
    }
}
</script>

// REACT/reactservicios/src/Components/Departamentos/InsertarDepartamento.js
import axios from "axios";
import Global from "../../Global";
import { Redirect } from "react-router";
import React, { Component } from "react";

export default class InsertarDepartamento extends Component {
  cajaNum = React.createRef();
  cajaNom = React.createRef();
  cajaLoc = React.createRef();

  state = {
    mensaje: "",
    status: false,
  };

  insertarDepartamento = (e) => {
    e.preventDefault();
    var num = this.cajaNum.current.value;
    var nom = this.cajaNom.current.value;
    var loc = this.cajaLoc.current.value;

    var departamento = {
      numero: parseInt(num),
      nombre: nom,
      localidad: loc,
    };

    var request = "/webresources/departamentos/post";
    var url = Global.urlCrudDepartamentos + request;
    axios.post(url, departamento).then((res) => {
      this.setState({
        mensaje: "Departamento insertado correctamente",
        status: true,
      });
    });
  };

  render() {
    if (this.state.status === true) {
      return <Redirect to="/departamentos" />;
    }
    return (
      <div className="row justify-content-center">
        <div className="col-4">
          <h1>Insertar Departamentos</h1>
          {this.state.status === true && (
            <h2
              style={{
                color: "green",
                padding: "5px",
                backgroundColor: "lightgreen",
              }}
            >
              {this.state.mensaje}
            </h2>
          )}
          <form onSubmit={this.insertarDepartamento}>
            <div className="form-group row mb-4">
              <label>Número: </label>
              <input type="text" className="form-control" ref={this.cajaNum} />
            </div>
            <div className="form-group row mb-4">
              <label>Nombre: </label>
              <input type="text" className="form-control" ref={this.cajaNom} />
            </div>
            <div className="form-group row mb-4">
              <label>Localidad: </label>
              <input type="text" className="form-control" ref={this.cajaLoc} />
            </div>
            <button className="btn btn-outline-success">
              Insertar Departamento
            </button>
          </form>
        </div>
      </div>
    );
  }
}
