// VUE/futbolvue/src/components/Jugador.vue
<template>
        <div class="row justify-content-center">
        <div class="card col-8 p-0 mb-3 m-2 text-center">
            <div class="row g-0">
                <div class="card-header">
                    <h3 class="card-title">{{jugador.nombre}}</h3>
                </div>
                <div class="row justify-content-center">
                    <img :src="jugador.imagen" style="width: 350px" class="card-img img-fluid rounded-start" alt="nombreImagen">
                </div>
                <div class="card-body">
                    <p class="card-text">Posicion: {{jugador.posicion}}</p>
                    <p class="card-text">Nacimiento: {{jugador.fechaNacimiento}}</p>
                    <p class="card-text">Pais: {{jugador.pais}}</p>
                    <router-link :to="'/jugadores/'+jugador.idEquipo" class="btn btn-outline-success me-2">Volver</router-link>
                </div>
                
            </div>
        </div>
    </div>
</template>

<script>
import Equipos from '../services/equipos'

const service = new Equipos();
export default {
    name: "Jugador",
    data(){
        return{
            idJugador: 0,
            jugador: {},
        }
    },
    mounted(){
        this.idJugador = this.$route.params.idJugador
        this.obtenerJugador();
    },
    methods:{
        obtenerJugador(){
            service.getJugador(this.idJugador).then(res=>{
                this.jugador = res;
            })
        }
    }

}
</script>

// ANGULAR/championangular/src/app/Components/jugador/jugador.component.ts
import { Component, OnInit } from '@angular/core';
import { ChampiosService } from 'src/app/Services/champions.service';
import { ActivatedRoute,Params } from '@angular/router';
import { Jugador } from 'src/app/Models/Jugador';

@Component({
  selector: 'app-jugador',
  templateUrl: './jugador.component.html',
  styleUrls: ['./jugador.component.css']
})
export class JugadorComponent implements OnInit {

  public jugador!: Jugador;
  public idJugador!: string;

  constructor(
    private _service: ChampiosService,
    private _router: ActivatedRoute
  ) { }

  ngOnInit(): void {
    this._router.params.subscribe((params:Params)=>{
      this.idJugador = params["idJugador"]
      this.cargarJugador();
    })
  }

  cargarJugador(){
    this._service.getJugadorId(this.idJugador).subscribe(res=>{
      this.jugador = res
    })
  }

}

<div *ngIf="!jugador" class="d-flex justify-content-center">
  <div class="spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>
<div *ngIf="jugador" class="row justify-content-center">
  <div class="col-4">
    <div class="card mb-3 m-2 text-center">
      <div class="card-header">
        <h5 class="card-title">{{ jugador.nombre }}</h5>
      </div>
      <div class="row justify-content-center">
        <img
          src="{{ jugador.imagen }}"
          class="card-img-top card-img py-4"
          alt="{{ jugador.nombre }}"
          style="width: 350px"
        />
      </div>
      <div class="card-body">
        <h2 class="card-text">{{ jugador.posicion }}</h2>
        <p class="card-text">Fecha: {{ jugador.fechaNacimiento }}</p>
        <p class="card-text">Pais: {{ jugador.pais }}</p>
        <a
          [routerLink]="['/jugadores', jugador.idEquipo]"
          class="btn btn-outline-success"
          >Jugadores</a
        >
      </div>
    </div>
  </div>
</div>
