// EXAMEN/Examen - 19 de noviembre/examenvuebolq/src/components/buscador.vue
<template>
    
    <div>

<div>
  <div class="row row-cols-6 g-2">
    <div v-for="(pelicula,index) in peliculas" :key="index" class="col-2">
      <div class="card text-center">
        <div class="row justify-content-center">
          <img
            :src="pelicula.foto "
            class="card-img-top card-img py-4"
            :alt=" pelicula.titulo "
            style="width: 350px"
          />
        </div>
      </div>
    </div>
  </div>
</div>

    </div>

</template>

<script>
import Pelicula from './../services/peliculas'

const service = new Pelicula();
export default {
    name: "buscador",
    data(){
        return{
            datos: "",
            peliculas: []
        }
    },
    mounted(){
        this.datos = this.$route.params.parametros
        this.buscar()
    },
    methods:{
        buscar(){
            service.buscarPeliculas(this.datos).then(res=>{
                this.peliculas = res
            });
        }
    }
}
</script>

// EXAMEN/Examen - 19 de noviembre/examenangularbolq/src/app/Components/buscador/buscador.component.ts
import { Component, OnInit } from '@angular/core';
import { PeliculaService } from 'src/app/Services/pelicula.service';
import { ActivatedRoute,Params } from '@angular/router';
import { Pelicula } from 'src/app/Models/Pelicula';

@Component({
  selector: 'app-buscador',
  templateUrl: './buscador.component.html',
  styleUrls: ['./buscador.component.css']
})
export class BuscadorComponent implements OnInit {

  public peliculas!: Array<Pelicula>
  public parametro!: string

  constructor(private _service: PeliculaService, private _route:ActivatedRoute) { }

  ngOnInit(): void {
    this._route.params.subscribe((params: Params)=>{
        this.parametro = params["parametros"]
        this.cargarPeliculasBuscadas()
    })
  }

  cargarPeliculasBuscadas(){
    this._service.buscarPeliculas(this.parametro).subscribe(res=>{
      this.peliculas = res;
    })
  }

}

<div *ngIf="peliculas">
  <div class="row row-cols-6 g-2">
    <div *ngFor="let pelicula of peliculas" class="col-2">
      <div class="card text-center">
        <div class="row justify-content-center">
          <img
            src="{{ pelicula.foto }}"
            class="card-img-top card-img py-4"
            alt="{{ pelicula.titulo }}"
            style="width: 350px"
          />
        </div>
      </div>
    </div>
  </div>
</div>
