// REACT/championreact/src/Components/Equipos/Equipo.js
import axios from "axios";
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Global from "../../Global";

export default class Equipo extends Component {
  state = {
    equipo: {},
    status: false,
  };

  cargarEquipo = () => {
    var id = this.props.id;
    var request = "/api/Equipos/" + id;
    var url = Global.urlChampions + request;
    axios.get(url).then((res) => {
      this.setState({
        equipo: res.data,
        status: true,
      });
    });
  };

  componentDidMount = () => {
    this.cargarEquipo();
  };

  componentDidUpdate = (prevProps) => {
    if (prevProps.id !== this.props.id) {
      this.cargarEquipo();
    }
  };

  render() {
    if (this.state.status === true) {
      return (
        <div>
          <div className="mt-5 row justify-content-center">
            <div className="card col-8 p-0">
              <div className="card-header text-center">
                {this.state.equipo.nombre}
              </div>
              <div className="row justify-content-center">
                <img
                  src={this.state.equipo.imagen}
                  alt="nombre"
                  className="card-img py-3"
                  style={{ width: "300px" }}
                />
              </div>
              <div className="card-body">
                <h5 className="card-title text-center">
                  Champions: {this.state.equipo.champions}
                </h5>
                <p className="card-text">{this.state.equipo.descripcion}</p>
                <div className="row">
                  <div className="col-6 d-flex justify-content-end">
                    <Link
                      to={"/jugadores/" + this.props.id}
                      className="btn btn-success"
                    >
                      Jugadores
                    </Link>
                  </div>
                  <div className="col-6 d-flex justify-content-start">
                    <Link to="/" className="btn btn-primary">
                      Volver
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      );
    } else {
      return <h1>Cargando Equipo</h1>;
    }
  }
}

// VUE/futbolvue/src/components/Equipo.vue
<template>
    <div class="row justify-content-center">
        <div class="card col-8 p-0 mb-3 m-2 text-center">
            <div class="row g-0">
                <div class="card-header">
                    <h3 class="card-title">{{equipo.nombre}}</h3>
                </div>
                <div class="row justify-content-center">
                    <img :src="equipo.imagen" style="width: 350px" class="card-img img-fluid rounded-start" alt="nombreImagen">
                </div>
                <div class="card-body">
                    <h5 class="card-title">Champions: {{equipo.champions}}</h5>
                    <p class="card-text">{{equipo.descripcion}}</p>
                    <router-link :to="'/jugadores/'+equipo.idEquipo" class="btn btn-outline-success me-2">Jugadores</router-link>
                    <router-link to="/" class="btn btn-outline-danger ms-2">Volver</router-link>
                </div>
                
            </div>
        </div>
    </div>
</template>

<script>
import Equipos from '../services/equipos'

const service = new Equipos();
export default {
    name: "Equipo",
    data(){
        return{
            equipo: {},
            idEquipo: 0
        }
    },mounted(){
        this.idEquipo = this.$route.params.idEquipo
        this.obtenerEquipo();
    },
    methods:{
        obtenerEquipo(){
            service.getEquipo(this.idEquipo).then(res=>{
                this.equipo = res
            })
        }
    },

    watch:{
        '$route.params.idEquipo'(next,last){
                if(next != last){
                    this.idEquipo = next
                    this.obtenerEquipo();
                }
        }
    }

}
</script>
