// ANGULAR/championangular/src/app/Components/equipo/equipo.component.ts
import { Component, OnInit } from '@angular/core';
import { ChampiosService } from 'src/app/Services/champions.service';
import { ActivatedRoute,Params } from '@angular/router';
import { Equipo } from 'src/app/Models/Equipo';

@Component({
  selector: 'app-equipo',
  templateUrl: './equipo.component.html',
  styleUrls: ['./equipo.component.css']
})
export class EquipoComponent implements OnInit {

  public equipo!: Equipo
  public idEquipo!: string

  constructor(
    private _service:ChampiosService,
    private _router:ActivatedRoute,
    ) { }

  ngOnInit(): void {

    this._router.params.subscribe((params:Params)=>{
      this.idEquipo = params["idEquipo"]
      this.cargarJugador();
    })
    
  }

  cargarJugador(){
    this._service.getEquipoId(this.idEquipo).subscribe(res=>{
      this.equipo = res
    })
  }
}

<div *ngIf="!equipo" class="d-flex justify-content-center">
  <div class="spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

<div *ngIf="equipo" class="row justify-content-center">
  <div class="col-8">
    <div class="card mb-3 m-2 text-center">
      <div class="card-header">
        <h5 class="card-title">{{ equipo.nombre }}</h5>
      </div>
      <div class="row justify-content-center">
        <img
          src="{{ equipo.imagen }}"
          class="card-img-top card-img py-4"
          alt="{{ equipo.nombre }}"
          style="width: 350px"
        />
      </div>
      <div class="card-body">
        <p class="card-text fw-bold">Champions: {{ equipo.champions }}</p>
        <p class="card-text">{{ equipo.descripcion }}</p>
        <a
          [routerLink]="['/jugadores', equipo.idEquipo]"
          class="btn btn-outline-success mx-2"
          >Jugadores</a
        >
        <a [routerLink]="['/']" class="btn btn-outline-primary mx-2">Volver</a>
      </div>
    </div>
  </div>
</div>

// VUE/futbolvue/src/components/Equipo.vue
<template>
    <div class="row justify-content-center">
        <div class="card col-8 p-0 mb-3 m-2 text-center">
            <div class="row g-0">
                <div class="card-header">
                    <h3 class="card-title">{{equipo.nombre}}</h3>
                </div>
                <div class="row justify-content-center">
                    <img :src="equipo.imagen" style="width: 350px" class="card-img img-fluid rounded-start" alt="nombreImagen">
                </div>
                <div class="card-body">
                    <h5 class="card-title">Champions: {{equipo.champions}}</h5>
                    <p class="card-text">{{equipo.descripcion}}</p>
                    <router-link :to="'/jugadores/'+equipo.idEquipo" class="btn btn-outline-success me-2">Jugadores</router-link>
                    <router-link to="/" class="btn btn-outline-danger ms-2">Volver</router-link>
                </div>
                
            </div>
        </div>
    </div>
</template>

<script>
import Equipos from '../services/equipos'

const service = new Equipos();
export default {
    name: "Equipo",
    data(){
        return{
            equipo: {},
            idEquipo: 0
        }
    },mounted(){
        this.idEquipo = this.$route.params.idEquipo
        this.obtenerEquipo();
    },
    methods:{
        obtenerEquipo(){
            service.getEquipo(this.idEquipo).then(res=>{
                this.equipo = res
            })
        }
    },

    watch:{
        '$route.params.idEquipo'(next,last){
                if(next != last){
                    this.idEquipo = next
                    this.obtenerEquipo();
                }
        }
    }

}
</script>
