// ANGULAR/championangular/src/app/Components/jugadores/jugadores.component.ts
import { Component, OnInit } from '@angular/core';
import { ChampiosService } from 'src/app/Services/champions.service';
import { ActivatedRoute,Params } from '@angular/router';
import { Jugador } from 'src/app/Models/Jugador';

@Component({
  selector: 'app-jugadores',
  templateUrl: './jugadores.component.html',
  styleUrls: ['./jugadores.component.css']
})
export class JugadoresComponent implements OnInit {

  public jugadores!: Array<Jugador>
  public idEquipo!: string

  constructor(
    private _service: ChampiosService,
    private _router: ActivatedRoute,
  ) { }

  ngOnInit(): void {
    this._router.params.subscribe((params:Params)=>{
      this.idEquipo = params["idEquipo"]
      this.cargarEquipos();
    })
  }

  cargarEquipos(){
    this._service.getJugadoresEquiposId(this.idEquipo).subscribe(res=>{
      this.jugadores = res
    })
  }

}

<div class="row justify-content-center mt-5">
  <div *ngIf="!jugadores" class="d-flex justify-content-center">
    <div class="spinner-border" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
  <div *ngIf="jugadores" class="col-8 text-center">
    <div class="row justify-content-center">
      <div class="col-4 text-center">
        <a [routerLink]="['/equipo', idEquipo]" class="btn btn-outline-success"
          >Volver</a
        >
      </div>
    </div>
    <table
      class="
        table table-striped table-hover table-responsive table-bordered
        border-dark
      "
    >
      <thead
        class="fw-bold"
        style="background-color: midnightblue; color: white"
      >
        <tr>
          <td>nombre</td>
          <td>imagen</td>
          <td>detalles</td>
        </tr>
      </thead>
      <tbody class="table-info table-bordered border-dark">
        <tr *ngFor="let jugador of jugadores">
          <td>{{ jugador.nombre }}</td>
          <td><img src="{{ jugador.imagen }}" alt="{{ jugador.nombre }}" /></td>
          <td>
            <a
              [routerLink]="['/jugador', jugador.idJugador]"
              class="btn btn-outline-danger"
              >Detalles</a
            >
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// VUE/futbolvue/src/components/Jugadores.vue
<template>
    <div class="row justify-content-center mt-5">
        <div class="col-12 text-center my-3">
        <router-link class="btn btn-outline-danger" :to="'/equipos/'+idEquipo">Volver</router-link>
        </div>
    <div class="col-8 text-center">
        <table class="table table-striped table-hover table-responsive table-bordered border-dark">
            <thead class="fw-bold" style="background-color: midnightblue; color: white;">
                <tr>
                    <td>Nombre</td>
                    <td>Imagen</td>
                    <td>Accion</td>
                </tr>
            </thead>
            <tbody class="table-info table-bordered border-dark">
                <tr v-for="(jugador,index) in jugadores" :key="index">
                    <td>{{jugador.nombre}}</td>
                    <td><img :src="jugador.imagen"/></td>
                    <td><router-link :to="'/jugador/'+jugador.idJugador" class="btn btn-outline-success">Detalles</router-link></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</template>

<script>
import Equipos from '../services/equipos'

const service = new Equipos();
export default {
    name: "Jugadores",
    mounted(){
        this.idEquipo = this.$route.params.idEquipo
        this.obtenerJugadores();
    },
    data(){
        return{
            idEquipo: 0,
            jugadores: [],
        }
    },methods:{
        obtenerJugadores(){
            service.getJugadores(this.idEquipo).then(res=>{
                this.jugadores = res
            })
        }
    }
}
</script>
