// VUE/futbolvue/src/components/Menu.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Tenth navbar example">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample08"
            aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <router-link class="nav-link active" to="/new">Link</router-link>
                </li>
                <li class="nav-item dropdown">
                    <span class="nav-link dropdown-toggle" id="desplegable" data-bs-toggle="dropdown"
                        aria-expanded="false">Desplegable</span>
                    <ul class="dropdown-menu" aria-labelledby="desplegable">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
</template>

<script>
export default {
    name: "Menu"
}
</script>

// ANGULAR/rutasangular/src/app/Components/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  constructor(rutas : ActivatedRoute) {

    rutas.params.subscribe((parametros: Params)=>{
      
    })

   }

  ngOnInit(): void {
  }

}

<div>
  <nav
    class="navbar navbar-expand-lg navbar-dark bg-dark"
    aria-label="Tenth navbar example"
  >
    <div class="container-fluid">
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarsExample08"
        aria-controls="navbarsExample08"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div
        class="collapse navbar-collapse justify-content-md-center"
        id="navbarsExample08"
      >
        <ul class="navbar-nav">
          <li class="nav-item">
            <a [routerLink]="['/home']" class="nav-link active">Home</a>
          </li>
          <li class="nav-item">
            <a [routerLink]="['/cine']" class="nav-link active">Cine</a>
          </li>
          <li class="nav-item">
            <a [routerLink]="['/television']" class="nav-link active"
              >Television</a
            >
          </li>
          <li class="nav-item">
            <a [routerLink]="['/musica']" class="nav-link active">Musica</a>
          </li>
          <li class="nav-item">
            <a [routerLink]="['/numeroDoble']" class="nav-link active"
              >Numero Doble</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>
