// EXAMEN/Examen - 19 de noviembre/examenangularbolq/src/app/Components/pelicula/pelicula.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute,Params } from '@angular/router';
import { PeliculaService } from 'src/app/Services/pelicula.service';
import { Pelicula } from 'src/app/Models/Pelicula';
import { Genero } from 'src/app/Models/Genero';
import { Nacionalidad } from 'src/app/Models/Nacionalidad';
import { Router } from '@angular/router';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

  public peliculas!: Array<Pelicula>;
  public idGenero!: string;
  public idNacionalidad!: string;
  public peliculaSeleccionada!: Pelicula;
  public nombreGenero!: Genero
  public nombreNacionalidad!: Nacionalidad
  public lugar !: string;
  public eliminado!: boolean;
  public mostrarPelicula!: boolean;
  
  constructor(private _service:PeliculaService, private _route:ActivatedRoute, private _router:Router) {
    this.eliminado = false;
    this.mostrarPelicula = false;
   }

  ngOnInit(): void {
    this._route.params.subscribe((params:Params)=>{
      if(params["genero"] != null){
        this.idGenero = params["genero"]
        this.cargarPeliculasGen();
      }

      if(params["nacionalidad"] != null){
        this.idNacionalidad = params["nacionalidad"]
        this.cargarPeliculasNac();
      }
    })
  }

  cargarPeliculasNac(){
    this.mostrarPelicula = false
    this.eliminado = false
    this._service.getPeliculaNacionalidad(this.idNacionalidad).subscribe(res=>{
      this.peliculas = res;
    })
    this._service.getNacionalidadId(this.idNacionalidad).subscribe(res=>{
      this.nombreNacionalidad = res;
      this.lugar = this.nombreNacionalidad.nombre
    })
  }

  cargarPeliculasGen(){
    this.mostrarPelicula = false
    this.eliminado = false
    this._service.getPeliculaGenero(this.idGenero).subscribe(res=>{
      this.peliculas = res;
    })
    this._service.getGenerosId(this.idGenero).subscribe(res=>{
      this.nombreGenero = res
      this.lugar = this.nombreGenero.nombre
    })
  }

  cargarDetallesPelicula(id:number){
    this._service.getPeliculaId(id.toString()).subscribe(res=>{
      this.peliculaSeleccionada = res;
      this.mostrarPelicula = true;
    })
  }

  modificarGenero(event: any){
    this._service.modifyPeliculaGenero(event.idPelicula,event.idGenero).subscribe(res=>{
      this._router.navigate(['/peliculasGenero',event.idGenero])
      this.eliminado = false
    })
  }

  eliminarPelicula(event: any){
    this._service.deletePelicula(event.toString()).subscribe(res=>{
      this.eliminado = true
      this.mostrarPelicula = false
      this._route.params.subscribe((params:Params)=>{
        if(params["genero"] != null){
          this.cargarPeliculasGen();
        }else{
          if(params["nacionalidad"] != null){
            this.cargarPeliculasNac();
          }
        }
  
      })
    })
  }

}

<div *ngIf="!peliculas">
  <div class="d-flex justify-content-center">
    <div class="spinner-border" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
</div>
<h1 *ngIf="lugar">Peliculas de {{ lugar }}</h1>
<h1 *ngIf="eliminado == true" class="text-dark bg-success p-3">
  Pelicula Eliminada Correctamente
</h1>
<div *ngIf="peliculas">
  <div class="row row-cols-6 g-2">
    <div *ngFor="let pelicula of peliculas" class="col-2">
      <div class="card text-center">
        <div class="row justify-content-center">
          <img
            src="{{ pelicula.foto }}"
            class="card-img-top card-img py-4"
            alt="{{ pelicula.titulo }}"
            (click)="cargarDetallesPelicula(pelicula.idPelicula)"
            style="width: 350px"
          />
        </div>
      </div>
    </div>
  </div>
  <div *ngIf="peliculaSeleccionada && mostrarPelicula == true">
    <hr />

    <app-detalles-pelicula
      [pelicula]="peliculaSeleccionada"
      (modificar)="modificarGenero($event)"
      (eliminar)="eliminarPelicula($event)"
    ></app-detalles-pelicula>
  </div>
</div>

// EXAMEN/Examen - 19 de noviembre/examenvuebolq/src/components/pelicula.vue
<template>
<div>
        <div v-if="!peliculas">
    <div class="d-flex justify-content-center">
        <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
        </div>
    </div>

    </div>

    <h1>{{lugar}}</h1>
    <h1 v-if="eliminar==true">Se Elimino la pelicula</h1>
    <div>
        <div class="row row-cols-6 g-2">
    <div v-for="(pelicula,index) in peliculas" :key="index" class="col-2">
      <div class="card text-center">
        <div class="row justify-content-center">
          <img
            :src="pelicula.foto"
            class="card-img-top card-img py-4"
            :alt="pelicula.titulo"
            @click="cargarDetallesPelicula(pelicula.idPelicula)"
            style="width: 350px"
          />
        </div>
      </div>
    </div>
  </div>
    </div>

    <div v-if="peliculaSelect">
        <detallesPelicula :pelicula="peliculaSelect" v-on:modificar="modificarGenero" v-on:eliminar="eliminarPelicula"/>
    </div>
</div>
</template>

<script>
import Pelicula from './../services/peliculas'
import detallesPelicula from './detallesPelicula.vue'

const service = new Pelicula();
export default {
    name: "pelicula",
    components:{
        detallesPelicula
    },
    data(){
        return{
            peliculas: [],
            genero: {},
            nacionalidad: {},
            idGenero: "",
            idNacionalidad: "",
            peliculaSelect: null,
            lugar: "",
            eliminar: false
        }
    },
    mounted(){
        if(this.$route.params.idNacionalidad != null){
            this.idNacionalidad = this.$route.params.idNacionalidad
            this.cargarPeliculasNac()
        }
        if(this.$route.params.idGenero != null){
            this.idGenero = this.$route.params.idGenero
            this.cargarPeliculasGen()
        }
        
    },methods:{
        cargarPeliculasGen(){
            service.getPeliculasGenero(this.idGenero).then(res=>{
                this.peliculas = res
                this.eliminar = false;
            })
            service.getGenerosId(this.idGenero).then(res=>{
                this.genero = res
                this.lugar = this.genero.nombre
            })
        },
        cargarPeliculasNac(){
            service.getPeliculasNacionalidad(this.idNacionalidad).then(res=>{
                this.peliculas = res
                this.eliminar = false;
            })
            service.getNacionalidadId(this.idNacionalidad).then(res=>{
                this.nacionalidad = res
                this.lugar = this.nacionalidad.nombre
            })
        },
        cargarDetallesPelicula(id){
            service.getPeliculasId(id).then(res=>{
                this.peliculaSelect = res;
            })
        },modificarGenero(idPelicula,idGenero){
            service.modificarPelicula(idPelicula, idGenero).then(res=>{
                console.log(res)
                this.$router.push("/peliculasGenero/"+idGenero)
            })
        },eliminarPelicula(idPelicula){
            this.eliminar = true;
            this.peliculaSelect = null;
            service.deletePelicula(idPelicula).then(res=>{
                console.log(res)
                if(this.$route.params.idNacionalidad != null){
                    this.cargarPeliculasNac()
                }else{
                    if(this.$route.params.idGenero != null){
                        this.cargarPeliculasGen()
                    }
                }

            })
        }
    },watch:{
        '$route.params.idNacionalidad'(next,last){
                if(next != last && next != null){
                    this.idNacionalidad = next
                    this.peliculaSelect = null;
                    this.cargarPeliculasNac();
                }
        },
        
        '$route.params.idGenero'(next,last){
                if(next != last && next != null){
                    this.idGenero = next
                    this.peliculaSelect = null;
                    this.cargarPeliculasGen();
                }
        }
    

    }
}
</script>
