// VUE/seriesvue/src/components/Menu.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Tenth navbar example">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample08"
                aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <router-link to="/" class="nav-link active">Home</router-link>
                    </li>
                    <li class="nav-item dropdown">
                        <span class="nav-link dropdown-toggle" id="desplegable" data-bs-toggle="dropdown"
                            aria-expanded="false">Series</span>
                        <ul class="dropdown-menu" aria-labelledby="desplegable">
                            <li v-for="(serie,index) in series" :key="index"><router-link :to="'/series/'+serie.idSerie" class="dropdown-item">{{serie.nombre}}</router-link></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

<script>
import ServiceSeries from './../services/ServiceSeries'

const service = new ServiceSeries();
export default {
    name: "Menu",
    data(){
        return{
            series: [],
        }
    },
    methods:{
        cargarSeries(){
            service.getSeries().then(res=>{
                this.series = res
            })
        }
    },
    mounted(){
        this.cargarSeries();
    },
}
</script>

// ANGULAR/seriesangular/src/app/Components/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { SeriesService } from 'src/app/Services/series.service';
import { Serie } from 'src/app/Models/Serie'

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  public series!: Array<Serie>

  constructor(private _service: SeriesService) { }

  ngOnInit(): void {
    this.cargarSeries();
  }

  cargarSeries(){
    this._service.getSeries().subscribe(res=>{
      this.series = res
    })
  }

}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Tenth navbar example">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample08"
            aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a [routerLink]="['/newPersonajes']" class="nav-link active">Nuevo Personaje</a>
                </li>
                <li class="nav-item">
                    <a [routerLink]="['/modifyPersonajes']" class="nav-link active">Modificar Personaje</a>
                </li>
                <li class="nav-item dropdown">
                    <span class="nav-link dropdown-toggle" id="desplegable" data-bs-toggle="dropdown"
                        aria-expanded="false">Series</span>
                    <ul class="dropdown-menu" aria-labelledby="desplegable">
                        <li *ngFor="let serie of series">
                            <a [routerLink]="['/serie/',serie.idSerie]" class="dropdown-item">{{serie.nombre}}</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
