// VUE/futbolvue/src/components/Jugador.vue
<template>
        <div class="row justify-content-center">
        <div class="card col-8 p-0 mb-3 m-2 text-center">
            <div class="row g-0">
                <div class="card-header">
                    <h3 class="card-title">{{jugador.nombre}}</h3>
                </div>
                <div class="row justify-content-center">
                    <img :src="jugador.imagen" style="width: 350px" class="card-img img-fluid rounded-start" alt="nombreImagen">
                </div>
                <div class="card-body">
                    <p class="card-text">Posicion: {{jugador.posicion}}</p>
                    <p class="card-text">Nacimiento: {{jugador.fechaNacimiento}}</p>
                    <p class="card-text">Pais: {{jugador.pais}}</p>
                    <router-link :to="'/jugadores/'+jugador.idEquipo" class="btn btn-outline-success me-2">Volver</router-link>
                </div>
                
            </div>
        </div>
    </div>
</template>

<script>
import Equipos from '../services/equipos'

const service = new Equipos();
export default {
    name: "Jugador",
    data(){
        return{
            idJugador: 0,
            jugador: {},
        }
    },
    mounted(){
        this.idJugador = this.$route.params.idJugador
        this.obtenerJugador();
    },
    methods:{
        obtenerJugador(){
            service.getJugador(this.idJugador).then(res=>{
                this.jugador = res;
            })
        }
    }

}
</script>

// REACT/championreact/src/Components/Jugadores/Jugador.js
import axios from "axios";
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Global from "../../Global";

export default class Jugador extends Component {
  state = {
    jugador: {},
    status: false,
  };

  cargarJugador = () => {
    var nombre = this.props.nombre;
    var request = "/api/Jugadores/BuscadorJugadores/" + nombre;
    var url = Global.urlChampions + request;
    axios.get(url).then((res) => {
      this.setState({
        jugador: res.data[0],
        status: true,
      });
    });
  };

  componentDidMount = () => {
    this.cargarJugador();
  };

  render() {
    if (this.state.status === true) {
      return (
        <div>
          <div className="mt-5 row justify-content-center">
            <div className="card col-8 p-0">
              <div className="card-header text-center">
                {this.state.jugador.nombre}
              </div>
              <div className="row justify-content-center">
                <img
                  src={this.state.jugador.imagen}
                  alt={this.state.jugador.nombre}
                  className="card-img py-3"
                  style={{ width: "300px" }}
                />
              </div>
              <div className="card-body text-center">
                <h5 className="card-title ">{this.state.jugador.posicion}</h5>
                <p>Fecha de Nacimiento: {this.state.jugador.fechaNacimiento}</p>
                <p>Pais: {this.state.jugador.pais}</p>
                <Link
                  to={"/jugadores/" + this.props.idEquipo}
                  className="btn btn-outline-success"
                >
                  Jugadores
                </Link>
              </div>
            </div>
          </div>
        </div>
      );
    } else {
      return <h1>Cargando jugador</h1>;
    }
  }
}
